import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';
import 'package:flutter_tts/flutter_tts.dart';

import '../../domain/entities/character.dart';
import '../constants/app_constants.dart';

/// Plays the pre-recorded pronunciation for a character.
///
/// Primary path  : assets/audio/letters/<character.id>.mp3
///                 (generated by scripts/generate_pronunciations.py)
/// Fallback path : flutter_tts speaks the character symbol live
///                 (works without generated files, useful during dev)
class LetterAudioService {
  final AudioPlayer _player = AudioPlayer();
  final FlutterTts _tts = FlutterTts();
  bool _ttsReady = false;

  Future<void> playLetter(Character character) async {
    final assetPath = 'audio/letters/${character.id}.mp3';

    // Try pre-recorded file first
    if (await _assetExists(assetPath)) {
      try {
        await _player.stop();
        await _player.play(AssetSource(assetPath), volume: 1.0);
        return;
      } catch (_) {
        // fall through to TTS
      }
    }

    // Fallback: live TTS
    await _speakFallback(character);
  }

  Future<void> stop() async {
    await _player.stop();
    await _tts.stop();
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// Returns true if the asset bundle contains [path].
  Future<bool> _assetExists(String path) async {
    try {
      await rootBundle.load('assets/$path');
      return true;
    } catch (_) {
      return false;
    }
  }

  Future<void> _speakFallback(Character character) async {
    if (!_ttsReady) {
      await _tts.setVolume(1.0);
      await _tts.setSpeechRate(0.45);
      await _tts.setPitch(1.1);
      _ttsReady = true;
    }
    await _tts.setLanguage(_localeFor(character.languageId));
    await _tts.stop();
    await _tts.speak('${character.name}. ${character.pronunciation}');
  }

  static String _localeFor(String languageId) {
    switch (languageId) {
      case 'malayalam': return 'ml-IN';
      case 'hindi':     return 'hi-IN';
      case 'tamil':     return 'ta-IN';
      default:          return 'en-US';
    }
  }

  void dispose() {
    _player.dispose();
    _tts.stop();
  }
}
